from .facultad_service import FacultadService
from .alumno_service import AlumnoService
from .tipodocumento_service import TipoDocumentoService
from .grado_service import GradoService
from .departamento_service import DepartamentoService
from .especialidad_service import EspecialidadService
from .tipoespecialidad_service import TipoEspecialidadService
from .universidad_service import UniversidadService
from .area_service import AreaService
from .grupo_service import GrupoService
from .plan_service import PlanService
from .materia_service import MateriaService
from .orientacion_service import OrientacionService
from .autoridad_service import AutoridadService
