from .home import home
from .universidad_resource import universidad_bp
from .area_resources import area_bp
from .tipodocumento_resources import tipodocumento_bp
from .tipodedicacion_resources import tipodedicacion_bp
from .categoriacargo_resources import categoriacargo_bp
from .grupo_resources import grupo_bp
from .grado_resources import grado_bp
from .departamento_resources import departamento_bp
from .certificado_resource import certificado_bp
from .tipo_especialidad_resources import tipo_especialidad_bp
from .plan_resources import plan_bp
from .alumno_resources import alumno_bp
from .facultad_resources import facultad_bp
from .autoridad_resources import autoridad_bp
from .cargo_resources import cargo_bp
from .especialidad_resources import especialidad_bp
from .materia_resources import materia_bp
from .orientacion_resources import orientacion_bp
