from .universidad_mapping import UniversidadMapping
from .alumno_mapping import AlumnoMapping
from .area_mapping import AreaMapping
from .autoridad_mapping import AutoridadMapping
from .categoriacargo_mapping import CategoriaCargoMapping
from .departamento_mapping import DepartamentoMapping
from .facultad_mapping import FacultadMapping
from .grado_mapping import GradoMapping
from .grupo_mapping import GrupoMapping
from .plan_mapping import PlanMapping
from .tipodedicacion_mapping import TipoDedicacionMapping
from .tipodocumento_mapping import TipoDocumentoMapping
from .tipo_especialidad_mapping import TipoEspecialidadMapping
from .cargo_mapping import CargoMapping
from .especialidad_mapping import EspecialidadMapping
from .materia_mapping import MateriaMapping
from .orientacion_mapping import OrientacionMapping
