from .autoridad import Autoridad
from .cargo import Cargo
from .categoria_cargo import CategoriaCargo
from .tipo_dedicacion import TipoDedicacion
from .facultad import Facultad
from .alumno import Alumno
from .tipodocumento import TipoDocumento
from .grado import Grado
from .grupo import Grupo
from .departamento import Departamento
from .especialidad import Especialidad
from .tipoespecialidad import TipoEspecialidad
from .materia import Materia
from .plan import Plan
from .orientacion import Orientacion
from .universidad import Universidad
from .area import Area
from .user import Usuario
from .nota import Nota

